### PR TITLE
Add partner force06

### LINKED ISSUE #37: Add Force 06 to partner section
AS we are going through a new partner for field experimentation, we shall add FORCE 06 to our partners in the section "Who do we work with?"

Below the related content suggestion :

- title: "FORCE 06"
- url: "https://www.departement06.fr/preservation-du-cadre-de-vie/force-06-3080.html"
- logo: "https://www.departement06.fr/documents/Usine/cg06/_logos/logo-bandeau-superieur.png"
- content: "Notre partenaire des alpes maritimes afin de diversifier les tests terrains"

### PR DESCRIPTION
**Pull request by fe51**
Hi there, 

This PR introduces the following modifications : 
- add Force06 in our partner section
- refactor partner sections
- fix some typos
- update engiegreen logo for better rendering
- add alternative desc to logo

image

Closes #37 

Happy to discuss it !

### CODE REVIEW

**Comment by fe51** [comment]
translations (spanish and catalan) have been made using [deepL](https://www.deepl.com/translator)

image

**Comment by fe51** [comment]
image

**Comment by MateoLostanlen** [comment]
it seems you have an issue with the english page 
image

**Comment by fe51** [comment]
Thank you for spotting this ! I had to reduce engie green logo in english to fit properly
Here are the screens in each langage

image

image

image
image

**Pull request merged**
