### PR TITLE
Ils parlent de nous section edit 

### PR DESCRIPTION
**Pull request by mondiriariana**
J'ai changed le config.yml pour ajouter ce lien https://www.techniques-ingenieur.fr/actualite/articles/comment-lia-permet-de-detecter-plus-rapidement-les-incendies-129238/?utm_source=linkedin&utm_medium=social&utm_campaign=72-WM-FY1LKDN&utm_content=ap_qgnbyezfjr et ce logo https://cdn.techniques-ingenieur.fr/lucy/ti/cdn.prod.v2.1.0/images/logo-eti.png

### CODE REVIEW

**Comment by fe51** [comment]
Hi there ! Thank you for your quick PR ! 

Before merging, could you just add a screenshot here to see how it render  ?

Thanks !

**Comment by mondiriariana** [comment]
Screenshot 2024-01-07 at 11 15 34 AM
Screenshot 2024-01-07 at 11 15 39 AM

**Comment by mondiriariana** [comment]
> Hi there ! Thank you for your quick PR !
> 
> Before merging, could you just add a screenshot here to see how it render ?
> 
> Thanks !

Screenshot 2024-01-07 at 11 15 34 AM
Screenshot 2024-01-07 at 11 15 39 AM

**Comment by mondiriariana** [comment]
> Hi there ! Thank you for your quick PR !
> 
> Before merging, could you just add a screenshot here to see how it render ?
> 
> Thanks !

Let me know if you'd like more changes.

**Review by fe51 — APPROVED** [review]
Thanks @mondiriariana !

**Pull request merged**
